import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import{getAuth,signInAnonymously}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import{getDatabase,ref,set,update,get,onValue,serverTimestamp,remove}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js";
const C=["Общение и любовь","Прощение и единство","Служение Богу и церкви","Забота и участие"],app=document.querySelector("#app"),params=new URLSearchParams(location.search);
let db,roomId=params.get("room"),data,timer;
function n(tag,a,...kids){const x=document.createElement(tag);a=a||{};Object.entries(a).forEach(([k,v])=>{if(k==="class")x.className=v;else if(k==="text")x.textContent=v;else if(k.startsWith("on"))x.addEventListener(k.slice(2).toLowerCase(),v);else if(k==="style")Object.assign(x.style,v);else x.setAttribute(k,v)});kids.flat().filter(Boolean).forEach(v=>x.append(v.nodeType?v:document.createTextNode(v)));return x}
const p=(x,c)=>n("p",{class:c||"",text:x}),h=(x,c)=>n(c||"h2",{text:x}),card=(...x)=>n("div",{class:"card"},x),btn=(x,c,fn,disabled)=>n("button",{class:"btn "+(c||""),text:x,onClick:fn,disabled:disabled||false}),view=(...x)=>app.replaceChildren(...x);
const users=()=>Object.values(data?.participants||{}),finished=()=>users().filter(x=>x.status==="finished"),sessionRef=path=>ref(db,"sessions/"+roomId+(path?"/"+path:""));
const per=(a,ids)=>{const v=ids.map(i=>a?.[i]).filter(x=>typeof x==="number");return v.length?Math.round(v.reduce((s,x)=>s+x,0)/(v.length*3)*100):0};
function error(text){view(n("section",{class:"screen"},card(p("ДИАГНОСТИКА","brand"),h("Нужно подключить базу","h1"),p(text,"muted"))))}
function newId(){return "F"+Math.random().toString(36).slice(2,7).toUpperCase()}
function participantURL(){return location.origin+location.pathname.replace("host.html","participant.html")+"?room="+encodeURIComponent(roomId)}
function settings(){if(users().length)return alert("Категорию можно выбрать только до подключения участников. Для новой темы откройте новую сессию.");const choice=prompt("Выберите категорию: 1 — Общение и любовь, 2 — Прощение и единство, 3 — Служение Богу и церкви, 4 — Забота и участие, 5 — все 16 вопросов.","5");const number=Number(choice);if(!number)return;const ids=number===5?Array.from({length:16},(_,i)=>i):number>=1&&number<=4?Array.from({length:4},(_,i)=>(number-1)*4+i):null;if(!ids)return alert("Введите число от 1 до 5.");update(sessionRef("meta"),{activeQuestions:ids})}
async function boot(){const cfg=window.FIREBASE_CONFIG;if(!cfg?.apiKey||String(cfg.apiKey).includes("ВСТАВЬТЕ"))return error("В файле firebase-config.js нужно вставить настройки Firebase. Это делается один раз.");try{initializeApp(cfg);db=getDatabase();await signInAnonymously(getAuth());if(!roomId){roomId=newId();history.replaceState({},"",location.pathname+"?room="+roomId)}if(!(await get(sessionRef("meta"))).exists())await set(sessionRef("meta"),{phase:"live",createdAt:serverTimestamp(),activeQuestions:Array.from({length:16},(_,i)=>i),limit:30});onValue(sessionRef(),snap=>{data=snap.val()||{};render()})}catch(e){error("Не удалось подключиться: "+e.message)}}
function stat(label,value,color,foot){return card(p(label,"muted"),n("strong",{class:color||"",text:value}),p(foot||"","small muted"))}
function averages(){const people=finished(),ids=data?.meta?.activeQuestions||[];return C.map((c,index)=>{const qids=ids.filter(i=>Math.floor(i/4)===index);return people.length?Math.round(people.reduce((s,x)=>s+per(x.answers,qids),0)/people.length):0})}
function bars(values){const box=n("div",{class:"bars"});C.forEach((c,i)=>{const value=values[i],row=n("div",{class:i%2?"gold":""},n("div",{class:"barlabel"},n("span",{text:c}),n("b",{text:value+"%"})),n("div",{class:"bar"},n("i",{style:{width:value+"%"}})));box.append(row)});return box}
function peopleList(){const box=n("div",{class:"participants"}),all=users();if(!all.length)return p("Пока никто не подключился по QR-коду.","muted");all.forEach(x=>box.append(n("div",{class:"person"},n("span",{text:x.name||"Участник"}),n("span",{class:"muted",text:x.status==="finished"?"готово · 100%":(x.progress||0)+"%"}))));return box}
function qrCard(){const url=participantURL();return card(h("Подключение участников","h3"),p("Попросите открыть камеру и отсканировать QR-код.","muted"),n("img",{class:"qr",alt:"QR-код для телефонов",src:"https://quickchart.io/qr?size=220&text="+encodeURIComponent(url)}),p("или перейти по ссылке","small muted"),p(url,"link"),n("div",{class:"actions"},btn("Скопировать ссылку","alt full",()=>navigator.clipboard.writeText(url))))}
function summaryCard(){const meta=data?.meta||{},phase=meta.phase,real=phase==="real",ideal=phase==="ideal",values=real?averages():ideal?[96,94,95,93]:averages();const label=real?"РЕАЛЬНЫЕ ДАННЫЕ":ideal?"ИДЕАЛЬНАЯ КАРТИНА":"ЭФИР В ПРОЦЕССЕ";const box=card(n("div",{class:"summarytop"},h("Общая картина","h3"),n("span",{class:"badge",text:label})),bars(values));box.classList.add("summary");return box}
function mainButton(){const phase=data?.meta?.phase||"live",complete=finished().length,total=users().length;if(phase==="live")return btn("Получить личные результаты","",()=>update(sessionRef("meta"),{phase:"personal"}),!complete||complete<total);if(phase==="personal")return btn("Показать общий экран","",()=>update(sessionRef("meta"),{phase:"ideal",idealStartedAt:Date.now()}));if(phase==="ideal")return btn("Показать реальные данные","",()=>update(sessionRef("meta"),{phase:"real"}));return btn("Новая сессия","",()=>location.href=location.pathname)}
function exportCSV(){const ids=data?.meta?.activeQuestions||[],head=["Никнейм","Статус","Прогресс","Общий результат"].concat(ids.map(i=>"Вопрос "+(i+1))),rows=[head];users().forEach(x=>{const a=x.answers||{};rows.push([x.name||"Участник",x.status||"",x.progress||0,per(a,ids)].concat(ids.map(i=>typeof a[i]==="number"?a[i]:""))) });const text="\ufeff"+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(";")).join("\n"),blob=new Blob([text],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="diagnostika-"+roomId+".csv";a.click();URL.revokeObjectURL(a.href)}
function render(){const all=users(),done=finished(),active=all.filter(x=>x.status!=="finished"),meta=data?.meta||{};clearTimeout(timer);if(meta.phase==="ideal"){const left=Math.max(0,(meta.idealStartedAt||Date.now()+30000)-Date.now()+30000);timer=setTimeout(()=>update(sessionRef("meta"),{phase:"real"}),left)}const top=n("div",{class:"top"},h("Диагностика атмосферы молодёжи","h1"),n("div",{class:"actions"},n("span",{class:"pill live"},n("i",{class:"statusdot"}),"ЭФИР АКТИВЕН"),btn("Настройки","alt small",settings)));const metrics=n("div",{class:"metrics"},stat("Подключились",all.length,"",all.length+" из 30 участников"),stat("Завершили",done.length,"green",done.length?"готовы к показу":"ожидаем ответы"),stat("Сейчас отвечают",active.length,"gold",active.length?"идёт диагностика":"все завершили"));const controls=n("div",{class:"bottom"},n("div",{},p(meta.phase==="live"?"Результаты откроются, когда все участники завершат тест.":meta.phase==="personal"?"Личные результаты уже открыты на телефонах.":meta.phase==="ideal"?"Сейчас на главном экране отображается почти идеальный результат.":"Отображаются реальные данные.","note")),n("div",{class:"actions"},mainButton(),btn("Экспорт Excel","alt",exportCSV)));const right=n("main",{},metrics,summaryCard(),controls,card(h("Участники","h3"),peopleList()));view(n("section",{class:"desktop"},n("div",{class:"shell"},top,p("Ведущий","small muted"),h("Сессия · "+roomId,"h3"),n("div",{class:"grid"},n("aside",{},qrCard()),right))))}
boot();
