import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import{getAuth,signInAnonymously}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import{getDatabase,ref,set,update,get,onValue,onDisconnect,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.12.5/firebase-database.js";
const Q=[
["Общение и любовь","Когда я прихожу на молодежку, я чувствую себя принятым и нужным.",["Да, часто чувствую это","Скорее да, но не всегда","Редко чувствую","Почти не чувствую"]],
["Общение и любовь","Я сам стараюсь замечать новых людей и подходить к тем, кто стоит в стороне.",["Да, стараюсь делать это","Иногда делаю","Редко делаю","Почти никогда"]],
["Общение и любовь","В нашей молодежи легко попросить о помощи, поддержке или молитве.",["Да, легко","Скорее легко","Не всегда легко","Сложно"]],
["Общение и любовь","Я чаще говорю людям слова поддержки, чем критикую или молчу.",["Да, это про меня","Стараюсь, но не всегда","Редко получается","Почти не делаю так"]],
["Прощение и единство","Если возникает обида, я стараюсь не копить ее, а решать мирно.",["Да, стараюсь сразу","Иногда решаю, иногда закрываюсь","Чаще коплю внутри","Обычно избегаю разговора"]],
["Прощение и единство","Я могу спокойно общаться с теми, кто отличается от меня характером или мнением.",["Да, могу","В основном могу","Иногда тяжело","Часто тяжело"]],
["Прощение и единство","В нашей молодежи больше единства, чем разделения на компании.",["Да, заметно больше единства","Скорее единства больше","Компании сильно ощущаются","Разделение очень заметно"]],
["Прощение и единство","Я готов первым сделать шаг к примирению, даже если мне неприятно.",["Да, готов","Скорее готов","Только иногда","Почти никогда"]],
["Служение Богу и церкви","Я понимаю, где могу быть полезен в молодежи или церкви.",["Да, понимаю","Примерно понимаю","Пока не очень","Совсем не понимаю"]],
["Служение Богу и церкви","Я участвую не только как зритель, но и как человек, который вкладывается.",["Да, регулярно","Иногда участвую","Редко участвую","Почти не участвую"]],
["Служение Богу и церкви","Служение для меня связано не только с обязанностью, но и с любовью к Богу и людям.",["Да, именно так","Скорее да","Иногда забываю об этом","Пока не чувствую так"]],
["Служение Богу и церкви","Я готов расти духовно и брать больше ответственности.",["Да, готов","Скорее готов","Пока сомневаюсь","Не готов"]],
["Забота и участие","Я замечаю, когда кому-то рядом одиноко, тяжело или нужна поддержка.",["Да, часто замечаю","Иногда замечаю","Редко замечаю","Почти не обращаю внимания"]],
["Забота и участие","Я готов помогать в простых практических делах, даже если это незаметно.",["Да, готов","Скорее готов","Только если попросят","Не очень готов"]],
["Забота и участие","Мне важно, чтобы молодежка была местом, где заботятся друг о друге.",["Да, очень важно","Важно, но не всегда думаю об этом","Скорее нейтрально","Пока не чувствую важности"]],
["Забота и участие","Я понимаю, что атмосфера начинается не с других, а лично с меня.",["Да, понимаю и принимаю","Скорее понимаю","Иногда забываю","Пока не согласен"]]];
const C=["Общение и любовь","Прощение и единство","Служение Богу и церкви","Забота и участие"],app=document.querySelector("#app"),params=new URLSearchParams(location.search),roomId=params.get("room"),device=localStorage.getItem("diagnostika-device")||crypto.randomUUID();
localStorage.setItem("diagnostika-device",device);let db,session,me;
function n(tag,a,...kids){const x=document.createElement(tag);a=a||{};Object.entries(a).forEach(([k,v])=>{if(k==="class")x.className=v;else if(k==="text")x.textContent=v;else if(k.startsWith("on"))x.addEventListener(k.slice(2).toLowerCase(),v);else if(k==="style")Object.assign(x.style,v);else x.setAttribute(k,v)});kids.flat().filter(Boolean).forEach(v=>x.append(v.nodeType?v:document.createTextNode(v)));return x}
const p=(x,c)=>n("p",{class:c||"",text:x}),h=(x,t)=>n(t||"h2",{text:x}),box=(...x)=>n("div",{class:"mcard"},x),btn=(x,c,fn)=>n("button",{class:"btn "+(c||""),text:x,onClick:fn}),view=(...x)=>app.replaceChildren(...x);
const r=path=>ref(db,"sessions/"+roomId+(path?"/"+path:"")),ids=()=>session?.meta?.activeQuestions||[],per=(a,ii)=>{const v=ii.map(i=>a?.[i]).filter(x=>typeof x==="number");return v.length?Math.round(v.reduce((s,x)=>s+x,0)/(v.length*3)*100):0};
function mobileOnly(){view(n("section",{class:"only-desktop screen"},box(h("Откройте QR‑код телефоном","h1"),p("Этот интерфейс предназначен только для участников на мобильном устройстве.","muted"))))}
function error(text){view(n("section",{class:"mobile"},n("div",{class:"phone"},p("ДИАГНОСТИКА","brand"),h("Не удалось подключиться","h1"),box(p(text,"muted")))))}
async function boot(){if(innerWidth>800)return mobileOnly();if(!roomId)return error("Сканируйте QR-код с экрана ведущего.");const cfg=window.FIREBASE_CONFIG;if(!cfg?.apiKey||String(cfg.apiKey).includes("ВСТАВЬТЕ"))return error("Firebase ещё не настроен.");try{initializeApp(cfg);db=getDatabase();await signInAnonymously(getAuth());if(!(await get(r("meta"))).exists())return error("Эта сессия уже завершена.");onValue(r(),s=>{session=s.val();session?render():error("Сессия завершена ведущим.")});onValue(r("participants/"+device),s=>{me=s.val();session&&render()})}catch(e){error("Ошибка подключения: "+e.message)}}
function joinView(){const input=n("input",{class:"field",placeholder:"Например, «Свет», «Данил»",maxlength:"24"});view(n("section",{class:"mobile"},n("div",{class:"phone"},n("span",{class:"tag",text:"ОНЛАЙН-ДИАГНОСТИКА"}),h("Атмосфера нашей молодёжи","h1"),p("Небольшая анонимная диагностика, которая помогает увидеть сильные стороны и точки роста.","muted"),box(h("Как тебя называть?","h2"),p("Можно указать имя или придумать никнейм — результаты всё равно останутся анонимными.","muted"),input,p("Это нужно только для твоей личной карточки.","small muted"),n("div",{class:"actions"},btn("Продолжить","full",()=>join(input.value)))))))}
async function join(name){const people=(await get(r("participants"))).val()||{};if(!people[device]&&Object.keys(people).length>=30)return alert("В этой сессии уже 30 участников.");await set(r("participants/"+device),{name:name.trim()||"Участник",status:"answering",progress:0,answers:{},joinedAt:Date.now(),online:true});await onDisconnect(r("participants/"+device+"/online")).set(false)}
function progress(number){return n("div",{class:"progress"},n("i",{style:{width:number+"%"}}))}
function render(){if(!me)return joinView();const phase=session.meta.phase;if(phase==="live")return questionView();if(phase==="personal"||phase==="ideal"||phase==="real")return personalView();waitingView()}
function questionView(){const ii=ids(),a=me.answers||{},id=ii.find(i=>typeof a[i]!=="number");if(id===undefined){if(me.status!=="finished")update(r("participants/"+device),{status:"finished",progress:100,completedAt:serverTimestamp()});return waitingView()}const pos=ii.indexOf(id),q=Q[id],answers=n("div",{});q[2].forEach((x,i)=>answers.append(n("button",{class:"answer",onClick:()=>reply(id,3-i,a,pos,ii.length)},n("span",{class:"letter",text:String.fromCharCode(65+i)}),n("span",{text:x}))));view(n("section",{class:"mobile"},n("div",{class:"phone"},p("ВОПРОС "+String(pos+1).padStart(2,"0")+" / "+ii.length,"brand"),p(q[0],"muted"),progress(Math.round(pos/ii.length*100)),h(q[1],"h1"),p("Выбери вариант, который ближе всего к тебе.","muted"),answers)))}
function reply(id,value,answers,pos,total){update(r("participants/"+device),{answers:Object.assign({},answers,{[id]:value}),status:"answering",progress:Math.round((pos+1)/total*100),lastSeen:serverTimestamp()})}
function waitingView(){view(n("section",{class:"mobile"},n("div",{class:"phone"},p("ГОТОВО","brand"),h("Спасибо за честность","h1"),box(p("Твои ответы сохранены.","muted"),p("Ведущий откроет твою личную карточку после того, как все завершат диагностику.","muted"),progress(100)))))}
function personalBars(){const box=n("div",{class:"mobile-results"}),a=me.answers||{};C.forEach((c,i)=>{const ii=ids().filter(x=>Math.floor(x/4)===i),v=per(a,ii);box.append(n("div",{class:"mobile-result-row"},n("div",{class:"barlabel"},n("span",{text:c}),n("b",{text:v+"%"})),n("div",{class:"bar"},n("i",{style:{width:v+"%"}}))))});return box}
function personalView(){const value=per(me.answers,ids());view(n("section",{class:"mobile"},n("div",{class:"phone"},p("ТВОЯ ЛИЧНАЯ КАРТОЧКА","brand"),h(me.name||"Участник","h1"),box(p("Твой результат","muted"),n("div",{class:"personal-score",text:value+"%"}),p(value>=75?"Ты помогаешь создавать тёплую атмосферу вокруг себя.":"Даже небольшой шаг к людям меняет атмосферу вокруг.","muted")),box(h("Твои показатели"),personalBars()),p("Любовь и дружба начинаются с меня.","muted"))))}
boot();
